### ISSUE TITLE
Driff lcd when rotate  with esp32_s3_lcd_ev_board

### ISSUE THREAD

**Issue by isthaison** [espressif/esp-ui#2]
![142E781B-87A0-45E5-94FB-568B11A1E137 (1)](https://github.com/user-attachments/assets/72a6a32c-6da0-41e5-9e8e-d70cc6a8bc74)
driff lcd when rotate 
![image](https://github.com/user-attachments/assets/907ae932-31ab-45d0-bf56-1b6a9d0f54cb)
![D87BCA5A-CE37-451F-A7A0-00D80A2A4939](https://github.com/user-attachments/assets/05587959-2c15-432b-993e-312509cb58d2)

**Comment by Lzw655** [comment]
Hi @isthaison,

Sorry, this is likely an RGB screen tearing issue. You can set `BSP_LCD_RGB_REFRESH_MODE` to `BSP_LCD_RGB_BOUNCE_BUFFER_MODE` to resolve it. By the way, you should disable the anti-tearing feature `BSP_DISPLAY_LVGL_AVOID_TEAR` before using LVGL rotation. Otherwise, it won't take effect.

Additionally, there are display issues when using LVGL software rotation with esp-ui, so it's currently recommended not to use LVGL rotation.

**Comment by isthaison** [comment]
I got it, thanks you

**Comment by chegewara** [comment]
Hi,
yes, it would be nice to have rotate working.
I just bought waveshare p4 nano with 10" display 800x1280 and i would prefer to not use it in portrait mode.
